### ISSUE TITLE
Why plt.savefig is not working?

### ISSUE THREAD

**Issue by masoud5676** [chraibi/cellular_automata#1]
i run your floor field cellular automata code on my python 2.7 win7 x32.
it run but just not produce any *.png file for me.
do you have any suggestion?

**Comment by chraibi** [comment]
Which script are you using?

**Comment by masoud5676** [comment]
i got this massages when i want to use plot_peds (line 119 to line 134) in
cellular_automaton.py

Thank you in advance.
[image: Inline image 2]

On Wed, Dec 9, 2015 at 2:08 AM, Mohcine Chraibi notifications@github.com
wrote:

> Which script are you using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chraibi/cellular_automata/issues/1#issuecomment-163042106
> .

## 

Masoud kh.fard , MSc Student
Department of Transportation Planning and Traffic Engineering
School of Civil engineering, Iran University of Science and Technology
(IUST)
Tehran - Iran.

**Comment by chraibi** [comment]
How do you call the script? Did you pass the `-P` option?

**Comment by masoud5676** [comment]
thank you
i can run it by changing the "os.path.join" direction

On Wed, Dec 9, 2015 at 12:44 PM, Mohcine Chraibi notifications@github.com
wrote:

> How do you call the script? Did you pass the -P option?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chraibi/cellular_automata/issues/1#issuecomment-163157751
> .

## 

Masoud kh.fard , MSc Student
Department of Transportation Planning and Traffic Engineering
School of Civil engineering, Iran University of Science and Technology
(IUST)
Tehran - Iran.

**Comment by chraibi** [comment]
you mean this line 

```
 figure_name = os.path.join('pngs', 'peds%.5d.png' % i) 
```

Could you please show specifically the change you did?

**Comment by masoud5676** [comment]
yes i changed to this and it worked
figure_name = os.path.join('E:/arshad/payan name/Python', 'peds%.5d.png' %
i)

I am currently preparing for M.S. thesis and want to calibrate floor field
Cellular automata with MLE.

On Thu, Dec 10, 2015 at 6:41 PM, Mohcine Chraibi notifications@github.com
wrote:

> you mean this line
> 
>  figure_name = os.path.join('pngs', 'peds%.5d.png' % i)
> 
> Could you please show specifically the change you did?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chraibi/cellular_automata/issues/1#issuecomment-163653930
> .

## 

Masoud kh.fard , MSc Student
Department of Transportation Planning and Traffic Engineering
School of Civil engineering, Iran University of Science and Technology
(IUST)
Tehran - Iran.

**Comment by chraibi** [comment]
the directory "pngs" did not exist before? 

Good luck for your thesis. You are welcome to contribute to this code.

**Comment by masoud5676** [comment]
no i had only "figs"
thank you so much
